lists/urls.py
from django.conf.urls import url
from lists import views

urlpatterns = [
	url(r'^new$', views.new_list, name='new_list'),
	url(r'^(\d+)/$', views.view_list, name='view_list'),
	# url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
	url(r'^$', list_views.home_page, name='home'),
	url(r'^lists/', include(list_urls)),
	url(r'^blog/', list_views.blog_page, name='blog'),
	# url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

class List(models.Model):
	
	def get_absolute_url(self):
		return reverse('view_list', args=[self.id])

class Item(models.Model):
	text = models.TextField(default='')
	list = models.ForeignKey(List, default=None)

lists/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import redirect, render
from lists.models import Item, List

def home_page(request):
	# comments = 'yey, waktunya berlibur'

	# if Item.objects.count() > 0:
	#	comments = 'sibuk tapi santai'

	# if Item.objects.count() >= 5:
	#	comments = 'oh tidak'

	# items = Item.objects.all()
	# return render(request, 'home.html', {'comments': comments})
	return render(request, 'home.html')

def view_list(request, list_id):
	list_ = List.objects.get(id=list_id)
	error = None

	if request.method == 'POST':
		try:
			item = Item(text=request.POST['item_text'], list=list_)
			item.full_clean()
			item.save()
			# return redirect('/lists/%d/' % (list_.id,))
			return redirect(list_)
		except ValidationError:
			error = "You can't have an empty list item"

	comment = 'yey, waktunya berlibur'
	count = Item.objects.filter(list_id=list_.id).count()

	if (count > 0) and (count < 5):
		comment = 'sibuk tapi santai'
	else:
		comment = 'oh tidak'
	#items = Item.objects.filter(list=list_)
	#return render(request, 'list.html', {'items': items})
	return render(request, 'list.html', {'list': list_, 'error': error, 'comment': comment})

def new_list(request):
	list_ = List.objects.create()
	item = Item(text=request.POST['item_text'], list=list_)
	try:
		item.full_clean()
		item.save()
	except ValidationError:
		list_.delete()
		error = "You can't have an empty list item"
		return render(request, 'home.html', {"error": error})
	# return redirect('view_list', list_.id)
	return redirect(list_)

# def add_item(request, list_id):
#	list_ = List.objects.get(id=list_id)
#	Item.objects.create(text=request.POST['item_text'], list=list_)
#	return redirect('/lists/%d/' % (list_.id,))

def blog_page(request):
	return render(request, 'index.html')

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>To-Do lists</title>
		<link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
		<link href="/static/base.css" rel="stylesheet">
	</head>

	<body>
		<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3 jumbotron">
					<div class="text-center">
						<h1>{% block header_text %}{% endblock %}</h1>
						<form method="POST" action="{% block form_action %}{% endblock %}">
							<input name="item_text" id="id_new_item"
								class="form-control input-lg"
								placeholder="Enter a to-do item"
							/>
							{% csrf_token %}
							{% if error %}
								<div class="form-group has-error">
									<span class="help-block">{{ error }}</span>
								</div>
							{% endif %}
						</form>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block comment %}
					{% endblock %}
				</div>
			</div>

			<div class="row">
				<div class="col-md-6 col-md-offset-3">
					{% block table %}
					{% endblock %}
				</div>
			</div>

			<!--<h3>{{ comments }}</h3>-->

		</div>
	</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>koeswirocana's</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/bootstrap/css/stylish-portfolio.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/bootstrap/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1 class="white-text">COMING SOON</h1>
            <p class="text-muted white-text">Copyright &copy; koeswirocana 2015</p>
        </div>
    </header>

</body>

</html>

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block comment %}<h3>{{ comment }}</h3>{% endblock %}

{% block table %}
	<table id="id_list_table" class="table">
		{% for item in list.item_set.all %}
			<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}